---
title: "yield_functions"
author: "Madeline Gorchels"
date: "5/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
source("./R/wheat_yield.R")

example_yields=read_csv("example_yield.csv")

wheat_input = example_yields %>% 
  select(year,yield_wheat) %>% 
  rename(mean_yield=yield_wheat)

wheat_yield(yields = wheat_input)

ggplot(wheat_input)+
  geom_histogram(aes(x=mean_yield), fill="burlywood3")+
  theme_classic()+
  ylab("Count")+
  xlab("Yield (tonnes/ha)")+
  scale_y_continuous(expand = c(0,0))

```

```{r}
source("./R/barley_yield.R")

barley_input = example_yields %>% 
  select(year,yield_barley) %>% 
  rename(mean_yield=yield_barley)

barley_yield(yields = barley_input)

ggplot(barley_input)+
  geom_histogram(aes(x=mean_yield), fill="burlywood3")+
  theme_classic()+
  ylab("Count")+
  xlab("Yield")+
  scale_y_continuous(expand = c(0,0))
```











##Reading in the data used to create a simple model 
```{r}
climate=read_csv("climate_change.csv")
```
```{r}
wheat=lm(yield_wheat~mean+precip.x,data=climate)
summary(wheat) 
#intercept = 1.1851971
#mean_T = -0.0317005
#precip = 0.0116212

barley = lm(yield_barley~mean+precip.x, data=climate)
summary(barley)
#intercept =  1.682980 
#mean_T =     -0.045015
#precip =      0.016502
```

# http://www.fao.org/3/y4011e04.htm
  #opitimal wheat temperature is 25 C
  #1 tonne/ha is average yield in Egypt with rain fed wheat
  # 1.42 tonne/ha is average barley yield 

